- name: set ha-mode to exactly two nodes for all queues for backup
  shell: rabbitmqctl set_policy ha-exactly-two ".*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
  register: res
  failed_when: res.rc != 0