---
- name: stop rabbitmq app
  shell: rabbitmqctl stop_app

- name: add this node to cluster
  shell: rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}

- name: start rabbitmq app
  shell: rabbitmqctl start_app
