---
- include: repository.yml

- include: hosts.yml
  when: update_hosts

- include: install.yml

- include: config_cluster.yml
  when: rabbitmq_create_cluster

- include: tls.yml
  when: enable_tls

- include: config.yml

- include: service.yml

- include: join_cluster.yml
  when: (rabbitmq_create_cluster == true) and ( ansible_fqdn != rabbitmq_cluster_master )

- meta: flush_handlers

- include: create_users.yml

- include: enable_ha_queues.yml
  when: backup_queues_in_two_nodes
